
language: node_js
node_js:
  - '8'
  - '10'
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test;'
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
